duti -s com.microsoft.VSCode .bsl all
duti -s com.microsoft.VSCode .os all
duti -s com.microsoft.VSCode .2da all
duti -s com.microsoft.VSCode .4dm all
duti -s com.microsoft.VSCode .abap all
duti -s com.microsoft.VSCode .asddls all
duti -s com.microsoft.VSCode .abnf all
duti -s com.microsoft.VSCode .asc all
duti -s com.microsoft.VSCode .ash all
duti -s com.microsoft.VSCode .aidl all
duti -s com.microsoft.VSCode .al all
duti -s com.microsoft.VSCode .ampl all
duti -s com.microsoft.VSCode .mod all
duti -s com.microsoft.VSCode .g4 all
duti -s com.microsoft.VSCode .apib all
duti -s com.microsoft.VSCode .apl all
duti -s com.microsoft.VSCode .dyalog all
duti -s com.microsoft.VSCode .asl all
duti -s com.microsoft.VSCode .dsl all
duti -s com.microsoft.VSCode .asn all
duti -s com.microsoft.VSCode .asn1 all
duti -s com.microsoft.VSCode .asax all
duti -s com.microsoft.VSCode .ascx all
duti -s com.microsoft.VSCode .ashx all
duti -s com.microsoft.VSCode .asmx all
duti -s com.microsoft.VSCode .aspx all
duti -s com.microsoft.VSCode .axd all
duti -s com.microsoft.VSCode .dats all
duti -s com.microsoft.VSCode .hats all
duti -s com.microsoft.VSCode .sats all
duti -s com.microsoft.VSCode .as all
duti -s com.microsoft.VSCode .adb all
duti -s com.microsoft.VSCode .ada all
duti -s com.microsoft.VSCode .ads all
duti -s com.microsoft.VSCode .txt all
duti -s com.microsoft.VSCode .afm all
duti -s com.microsoft.VSCode .agda all
duti -s com.microsoft.VSCode .als all
duti -s com.microsoft.VSCode .OutJob all
duti -s com.microsoft.VSCode .PcbDoc all
duti -s com.microsoft.VSCode .PrjPCB all
duti -s com.microsoft.VSCode .SchDoc all
duti -s com.microsoft.VSCode .as all
duti -s com.microsoft.VSCode .angelscript all
duti -s com.microsoft.VSCode .antlers.html all
duti -s com.microsoft.VSCode .antlers.php all
duti -s com.microsoft.VSCode .antlers.xml all
duti -s com.microsoft.VSCode .apacheconf all
duti -s com.microsoft.VSCode .vhost all
duti -s com.microsoft.VSCode .htaccess all
duti -s com.microsoft.VSCode .cls all
duti -s com.microsoft.VSCode .trigger all
duti -s com.microsoft.VSCode .agc all
duti -s com.microsoft.VSCode .applescript all
duti -s com.microsoft.VSCode .scpt all
duti -s com.microsoft.VSCode .arc all
duti -s com.microsoft.VSCode .asciidoc all
duti -s com.microsoft.VSCode .adoc all
duti -s com.microsoft.VSCode .asc all
duti -s com.microsoft.VSCode .aj all
duti -s com.microsoft.VSCode .asm all
duti -s com.microsoft.VSCode .a51 all
duti -s com.microsoft.VSCode .i all
duti -s com.microsoft.VSCode .inc all
duti -s com.microsoft.VSCode .nas all
duti -s com.microsoft.VSCode .nasm all
duti -s com.microsoft.VSCode .astro all
duti -s com.microsoft.VSCode .asy all
duti -s com.microsoft.VSCode .aug all
duti -s com.microsoft.VSCode .ahk all
duti -s com.microsoft.VSCode .ahkl all
duti -s com.microsoft.VSCode .au3 all
duti -s com.microsoft.VSCode .avdl all
duti -s com.microsoft.VSCode .awk all
duti -s com.microsoft.VSCode .auk all
duti -s com.microsoft.VSCode .gawk all
duti -s com.microsoft.VSCode .mawk all
duti -s com.microsoft.VSCode .nawk all
duti -s com.microsoft.VSCode .bas all
duti -s com.microsoft.VSCode .bal all
duti -s com.microsoft.VSCode .bat all
duti -s com.microsoft.VSCode .cmd all
duti -s com.microsoft.VSCode .bf all
duti -s com.microsoft.VSCode .befunge all
duti -s com.microsoft.VSCode .bf all
duti -s com.microsoft.VSCode .be all
duti -s com.microsoft.VSCode .bib all
duti -s com.microsoft.VSCode .bibtex all
duti -s com.microsoft.VSCode .bicep all
duti -s com.microsoft.VSCode .bs all
duti -s com.microsoft.VSCode .bison all
duti -s com.microsoft.VSCode .bb all
duti -s com.microsoft.VSCode .blade all
duti -s com.microsoft.VSCode .blade.php all
duti -s com.microsoft.VSCode .bb all
duti -s com.microsoft.VSCode .decls all
duti -s com.microsoft.VSCode .bmx all
duti -s com.microsoft.VSCode .bsv all
duti -s com.microsoft.VSCode .bs all
duti -s com.microsoft.VSCode .boo all
duti -s com.microsoft.VSCode .bpl all
duti -s com.microsoft.VSCode .b all
duti -s com.microsoft.VSCode .bf all
duti -s com.microsoft.VSCode .bs all
duti -s com.microsoft.VSCode .brs all
duti -s com.microsoft.VSCode .browserslistrc all
duti -s com.microsoft.VSCode .c all
duti -s com.microsoft.VSCode .cats all
duti -s com.microsoft.VSCode .h all
duti -s com.microsoft.VSCode .idc all
duti -s com.microsoft.VSCode .cs all
duti -s com.microsoft.VSCode .cake all
duti -s com.microsoft.VSCode .csx all
duti -s com.microsoft.VSCode .linq all
duti -s com.microsoft.VSCode .cpp all
duti -s com.microsoft.VSCode .c++ all
duti -s com.microsoft.VSCode .cc all
duti -s com.microsoft.VSCode .cp all
duti -s com.microsoft.VSCode .cppm all
duti -s com.microsoft.VSCode .cxx all
duti -s com.microsoft.VSCode .h all
duti -s com.microsoft.VSCode .h++ all
duti -s com.microsoft.VSCode .hh all
duti -s com.microsoft.VSCode .hpp all
duti -s com.microsoft.VSCode .hxx all
duti -s com.microsoft.VSCode .inc all
duti -s com.microsoft.VSCode .inl all
duti -s com.microsoft.VSCode .ino all
duti -s com.microsoft.VSCode .ipp all
duti -s com.microsoft.VSCode .ixx all
duti -s com.microsoft.VSCode .re all
duti -s com.microsoft.VSCode .tcc all
duti -s com.microsoft.VSCode .tpp all
duti -s com.microsoft.VSCode .txx all
duti -s com.microsoft.VSCode .c-objdump all
duti -s com.microsoft.VSCode .chs all
duti -s com.microsoft.VSCode .cds all
duti -s com.microsoft.VSCode .cil all
duti -s com.microsoft.VSCode .clp all
duti -s com.microsoft.VSCode .cmake all
duti -s com.microsoft.VSCode .cmake.in all
duti -s com.microsoft.VSCode .cob all
duti -s com.microsoft.VSCode .cbl all
duti -s com.microsoft.VSCode .ccp all
duti -s com.microsoft.VSCode .cobol all
duti -s com.microsoft.VSCode .cpy all
duti -s com.microsoft.VSCode .dae all
duti -s com.microsoft.VSCode .cson all
duti -s com.microsoft.VSCode .css all
duti -s com.microsoft.VSCode .csv all
duti -s com.microsoft.VSCode .cue all
duti -s com.microsoft.VSCode .w all
duti -s com.microsoft.VSCode .cabal all
duti -s com.microsoft.VSCode .cdc all
duti -s com.microsoft.VSCode .cairo all
duti -s com.microsoft.VSCode .mligo all
duti -s com.microsoft.VSCode .capnp all
duti -s com.microsoft.VSCode .mss all
duti -s com.microsoft.VSCode .ceylon all
duti -s com.microsoft.VSCode .chpl all
duti -s com.microsoft.VSCode .ch all
duti -s com.microsoft.VSCode .crc32 all
duti -s com.microsoft.VSCode .md2 all
duti -s com.microsoft.VSCode .md4 all
duti -s com.microsoft.VSCode .md5 all
duti -s com.microsoft.VSCode .sha1 all
duti -s com.microsoft.VSCode .sha2 all
duti -s com.microsoft.VSCode .sha224 all
duti -s com.microsoft.VSCode .sha256 all
duti -s com.microsoft.VSCode .sha256sum all
duti -s com.microsoft.VSCode .sha3 all
duti -s com.microsoft.VSCode .sha384 all
duti -s com.microsoft.VSCode .sha512 all
duti -s com.microsoft.VSCode .ck all
duti -s com.microsoft.VSCode .circom all
duti -s com.microsoft.VSCode .cirru all
duti -s com.microsoft.VSCode .clw all
duti -s com.microsoft.VSCode .clar all
duti -s com.microsoft.VSCode .asp all
duti -s com.microsoft.VSCode .icl all
duti -s com.microsoft.VSCode .dcl all
duti -s com.microsoft.VSCode .click all
duti -s com.microsoft.VSCode .clj all
duti -s com.microsoft.VSCode .bb all
duti -s com.microsoft.VSCode .boot all
duti -s com.microsoft.VSCode .cl2 all
duti -s com.microsoft.VSCode .cljc all
duti -s com.microsoft.VSCode .cljs all
duti -s com.microsoft.VSCode .cljs.hl all
duti -s com.microsoft.VSCode .cljscm all
duti -s com.microsoft.VSCode .cljx all
duti -s com.microsoft.VSCode .hic all
duti -s com.microsoft.VSCode .soy all
duti -s com.microsoft.VSCode .conllu all
duti -s com.microsoft.VSCode .conll all
duti -s com.microsoft.VSCode .ql all
duti -s com.microsoft.VSCode .qll all
duti -s com.microsoft.VSCode .coffee all
duti -s com.microsoft.VSCode ._coffee all
duti -s com.microsoft.VSCode .cake all
duti -s com.microsoft.VSCode .cjsx all
duti -s com.microsoft.VSCode .iced all
duti -s com.microsoft.VSCode .cfm all
duti -s com.microsoft.VSCode .cfml all
duti -s com.microsoft.VSCode .cfc all
duti -s com.microsoft.VSCode .lisp all
duti -s com.microsoft.VSCode .asd all
duti -s com.microsoft.VSCode .cl all
duti -s com.microsoft.VSCode .l all
duti -s com.microsoft.VSCode .lsp all
duti -s com.microsoft.VSCode .ny all
duti -s com.microsoft.VSCode .podsl all
duti -s com.microsoft.VSCode .sexp all
duti -s com.microsoft.VSCode .cwl all
duti -s com.microsoft.VSCode .cp all
duti -s com.microsoft.VSCode .cps all
duti -s com.microsoft.VSCode .cl all
duti -s com.microsoft.VSCode .coq all
duti -s com.microsoft.VSCode .v all
duti -s com.microsoft.VSCode .cppobjdump all
duti -s com.microsoft.VSCode .c++-objdump all
duti -s com.microsoft.VSCode .c++objdump all
duti -s com.microsoft.VSCode .cpp-objdump all
duti -s com.microsoft.VSCode .cxx-objdump all
duti -s com.microsoft.VSCode .creole all
duti -s com.microsoft.VSCode .cr all
duti -s com.microsoft.VSCode .orc all
duti -s com.microsoft.VSCode .udo all
duti -s com.microsoft.VSCode .csd all
duti -s com.microsoft.VSCode .sco all
duti -s com.microsoft.VSCode .cu all
duti -s com.microsoft.VSCode .cuh all
duti -s com.microsoft.VSCode .cue all
duti -s com.microsoft.VSCode .curry all
duti -s com.microsoft.VSCode .cy all
duti -s com.microsoft.VSCode .cyp all
duti -s com.microsoft.VSCode .cypher all
duti -s com.microsoft.VSCode .pyx all
duti -s com.microsoft.VSCode .pxd all
duti -s com.microsoft.VSCode .pxi all
duti -s com.microsoft.VSCode .d all
duti -s com.microsoft.VSCode .di all
duti -s com.microsoft.VSCode .d-objdump all
duti -s com.microsoft.VSCode .d2 all
duti -s com.microsoft.VSCode .com all
duti -s com.microsoft.VSCode .dm all
duti -s com.microsoft.VSCode .zone all
duti -s com.microsoft.VSCode .arpa all
duti -s com.microsoft.VSCode .d all
duti -s com.microsoft.VSCode .dfy all
duti -s com.microsoft.VSCode .darcspatch all
duti -s com.microsoft.VSCode .dpatch all
duti -s com.microsoft.VSCode .dart all
duti -s com.microsoft.VSCode .dwl all
duti -s com.microsoft.VSCode .dsc all
duti -s com.microsoft.VSCode .dsc all
duti -s com.microsoft.VSCode .dhall all
duti -s com.microsoft.VSCode .diff all
duti -s com.microsoft.VSCode .patch all
duti -s com.microsoft.VSCode .x all
duti -s com.microsoft.VSCode .dockerfile all
duti -s com.microsoft.VSCode .djs all
duti -s com.microsoft.VSCode .env all
duti -s com.microsoft.VSCode .env all
duti -s com.microsoft.VSCode .env.ci all
duti -s com.microsoft.VSCode .env.dev all
duti -s com.microsoft.VSCode .env.development all
duti -s com.microsoft.VSCode .env.development.local all
duti -s com.microsoft.VSCode .env.example all
duti -s com.microsoft.VSCode .env.local all
duti -s com.microsoft.VSCode .env.prod all
duti -s com.microsoft.VSCode .env.production all
duti -s com.microsoft.VSCode .env.staging all
duti -s com.microsoft.VSCode .env.test all
duti -s com.microsoft.VSCode .env.testing all
duti -s com.microsoft.VSCode .dylan all
duti -s com.microsoft.VSCode .dyl all
duti -s com.microsoft.VSCode .intr all
duti -s com.microsoft.VSCode .lid all
duti -s com.microsoft.VSCode .e all
duti -s com.microsoft.VSCode .eml all
duti -s com.microsoft.VSCode .mbox all
duti -s com.microsoft.VSCode .ebnf all
duti -s com.microsoft.VSCode .ecl all
duti -s com.microsoft.VSCode .eclxml all
duti -s com.microsoft.VSCode .ecl all
duti -s com.microsoft.VSCode .ejs all
duti -s com.microsoft.VSCode .ect all
duti -s com.microsoft.VSCode .ejs.t all
duti -s com.microsoft.VSCode .jst all
duti -s com.microsoft.VSCode .eq all
duti -s com.microsoft.VSCode .sch all
duti -s com.microsoft.VSCode .brd all
duti -s com.microsoft.VSCode .eb all
duti -s com.microsoft.VSCode .epj all
duti -s com.microsoft.VSCode .html all
duti -s com.microsoft.VSCode .edgeql all
duti -s com.microsoft.VSCode .esdl all
duti -s com.microsoft.VSCode .editorconfig all
duti -s com.microsoft.VSCode .editorconfig all
duti -s com.microsoft.VSCode .edc all
duti -s com.microsoft.VSCode .e all
duti -s com.microsoft.VSCode .ex all
duti -s com.microsoft.VSCode .exs all
duti -s com.microsoft.VSCode .elm all
duti -s com.microsoft.VSCode .elv all
duti -s com.microsoft.VSCode .abbrev_defs all
duti -s com.microsoft.VSCode .emacs all
duti -s com.microsoft.VSCode .emacs.desktop all
duti -s com.microsoft.VSCode .gnus all
duti -s com.microsoft.VSCode .spacemacs all
duti -s com.microsoft.VSCode .viper all
duti -s com.microsoft.VSCode .el all
duti -s com.microsoft.VSCode .emacs all
duti -s com.microsoft.VSCode .emacs.desktop all
duti -s com.microsoft.VSCode .em all
duti -s com.microsoft.VSCode .emberscript all
duti -s com.microsoft.VSCode .erl all
duti -s com.microsoft.VSCode .app all
duti -s com.microsoft.VSCode .app.src all
duti -s com.microsoft.VSCode .es all
duti -s com.microsoft.VSCode .escript all
duti -s com.microsoft.VSCode .hrl all
duti -s com.microsoft.VSCode .xrl all
duti -s com.microsoft.VSCode .yrl all
duti -s com.microsoft.VSCode .e all
duti -s com.microsoft.VSCode .ex all
duti -s com.microsoft.VSCode .fs all
duti -s com.microsoft.VSCode .fsi all
duti -s com.microsoft.VSCode .fsx all
duti -s com.microsoft.VSCode .fst all
duti -s com.microsoft.VSCode .fsti all
duti -s com.microsoft.VSCode .flf all
duti -s com.microsoft.VSCode .fx all
duti -s com.microsoft.VSCode .flux all
duti -s com.microsoft.VSCode .factor all
duti -s com.microsoft.VSCode .factor-boot-rc all
duti -s com.microsoft.VSCode .factor-rc all
duti -s com.microsoft.VSCode .fy all
duti -s com.microsoft.VSCode .fancypack all
duti -s com.microsoft.VSCode .fan all
duti -s com.microsoft.VSCode .dsp all
duti -s com.microsoft.VSCode .fnl all
duti -s com.microsoft.VSCode .f all
duti -s com.microsoft.VSCode .fs all
duti -s com.microsoft.VSCode .ftl all
duti -s com.microsoft.VSCode .for all
duti -s com.microsoft.VSCode .eam.fs all
duti -s com.microsoft.VSCode .fth all
duti -s com.microsoft.VSCode .4th all
duti -s com.microsoft.VSCode .f all
duti -s com.microsoft.VSCode .for all
duti -s com.microsoft.VSCode .forth all
duti -s com.microsoft.VSCode .fr all
duti -s com.microsoft.VSCode .frt all
duti -s com.microsoft.VSCode .fs all
duti -s com.microsoft.VSCode .f all
duti -s com.microsoft.VSCode .f77 all
duti -s com.microsoft.VSCode .for all
duti -s com.microsoft.VSCode .fpp all
duti -s com.microsoft.VSCode .f90 all
duti -s com.microsoft.VSCode .f03 all
duti -s com.microsoft.VSCode .f08 all
duti -s com.microsoft.VSCode .f95 all
duti -s com.microsoft.VSCode .bi all
duti -s com.microsoft.VSCode .bas all
duti -s com.microsoft.VSCode .ftl all
duti -s com.microsoft.VSCode .fr all
duti -s com.microsoft.VSCode .fut all
duti -s com.microsoft.VSCode .g all
duti -s com.microsoft.VSCode .cnc all
duti -s com.microsoft.VSCode .gco all
duti -s com.microsoft.VSCode .gcode all
duti -s com.microsoft.VSCode .gaml all
duti -s com.microsoft.VSCode .gms all
duti -s com.microsoft.VSCode .g all
duti -s com.microsoft.VSCode .gap all
duti -s com.microsoft.VSCode .gd all
duti -s com.microsoft.VSCode .gi all
duti -s com.microsoft.VSCode .tst all
duti -s com.microsoft.VSCode .md all
duti -s com.microsoft.VSCode .gdb all
duti -s com.microsoft.VSCode .gdbinit all
duti -s com.microsoft.VSCode .gd all
duti -s com.microsoft.VSCode .ged all
duti -s com.microsoft.VSCode .glsl all
duti -s com.microsoft.VSCode .fp all
duti -s com.microsoft.VSCode .frag all
duti -s com.microsoft.VSCode .frg all
duti -s com.microsoft.VSCode .fs all
duti -s com.microsoft.VSCode .fsh all
duti -s com.microsoft.VSCode .fshader all
duti -s com.microsoft.VSCode .geo all
duti -s com.microsoft.VSCode .geom all
duti -s com.microsoft.VSCode .glslf all
duti -s com.microsoft.VSCode .glslv all
duti -s com.microsoft.VSCode .gs all
duti -s com.microsoft.VSCode .gshader all
duti -s com.microsoft.VSCode .rchit all
duti -s com.microsoft.VSCode .rmiss all
duti -s com.microsoft.VSCode .shader all
duti -s com.microsoft.VSCode .tesc all
duti -s com.microsoft.VSCode .tese all
duti -s com.microsoft.VSCode .vert all
duti -s com.microsoft.VSCode .vrx all
duti -s com.microsoft.VSCode .vs all
duti -s com.microsoft.VSCode .vsh all
duti -s com.microsoft.VSCode .vshader all
duti -s com.microsoft.VSCode .gn all
duti -s com.microsoft.VSCode .gni all
duti -s com.microsoft.VSCode .gn all
duti -s com.microsoft.VSCode .gsc all
duti -s com.microsoft.VSCode .csc all
duti -s com.microsoft.VSCode .gsh all
duti -s com.microsoft.VSCode .gml all
duti -s com.microsoft.VSCode .gmi all
duti -s com.microsoft.VSCode .4gl all
duti -s com.microsoft.VSCode .per all
duti -s com.microsoft.VSCode .gs all
duti -s com.microsoft.VSCode .kid all
duti -s com.microsoft.VSCode .ebuild all
duti -s com.microsoft.VSCode .eclass all
duti -s com.microsoft.VSCode .gbr all
duti -s com.microsoft.VSCode .cmp all
duti -s com.microsoft.VSCode .gbl all
duti -s com.microsoft.VSCode .gbo all
duti -s com.microsoft.VSCode .gbp all
duti -s com.microsoft.VSCode .gbs all
duti -s com.microsoft.VSCode .gko all
duti -s com.microsoft.VSCode .gml all
duti -s com.microsoft.VSCode .gpb all
duti -s com.microsoft.VSCode .gpt all
duti -s com.microsoft.VSCode .gtl all
duti -s com.microsoft.VSCode .gto all
duti -s com.microsoft.VSCode .gtp all
duti -s com.microsoft.VSCode .gts all
duti -s com.microsoft.VSCode .ncl all
duti -s com.microsoft.VSCode .sol all
duti -s com.microsoft.VSCode .po all
duti -s com.microsoft.VSCode .pot all
duti -s com.microsoft.VSCode .feature all
duti -s com.microsoft.VSCode .story all
duti -s com.microsoft.VSCode .gitattributes all
duti -s com.microsoft.VSCode .gitconfig all
duti -s com.microsoft.VSCode .gitconfig all
duti -s com.microsoft.VSCode .gitmodules all
duti -s com.microsoft.VSCode .git-blame-ignore-revs all
duti -s com.microsoft.VSCode .gleam all
duti -s com.microsoft.VSCode .gjs all
duti -s com.microsoft.VSCode .glf all
duti -s com.microsoft.VSCode .bdf all
duti -s com.microsoft.VSCode .gp all
duti -s com.microsoft.VSCode .gnu all
duti -s com.microsoft.VSCode .gnuplot all
duti -s com.microsoft.VSCode .p all
duti -s com.microsoft.VSCode .plot all
duti -s com.microsoft.VSCode .plt all
duti -s com.microsoft.VSCode .go all
duti -s com.microsoft.VSCode .gdnlib all
duti -s com.microsoft.VSCode .gdns all
duti -s com.microsoft.VSCode .tres all
duti -s com.microsoft.VSCode .tscn all
duti -s com.microsoft.VSCode .golo all
duti -s com.microsoft.VSCode .gs all
duti -s com.microsoft.VSCode .gst all
duti -s com.microsoft.VSCode .gsx all
duti -s com.microsoft.VSCode .vark all
duti -s com.microsoft.VSCode .grace all
duti -s com.microsoft.VSCode .gradle all
duti -s com.microsoft.VSCode .gradle.kts all
duti -s com.microsoft.VSCode .gf all
duti -s com.microsoft.VSCode .gml all
duti -s com.microsoft.VSCode .graphql all
duti -s com.microsoft.VSCode .gql all
duti -s com.microsoft.VSCode .graphqls all
duti -s com.microsoft.VSCode .dot all
duti -s com.microsoft.VSCode .gv all
duti -s com.microsoft.VSCode .groovy all
duti -s com.microsoft.VSCode .grt all
duti -s com.microsoft.VSCode .gtpl all
duti -s com.microsoft.VSCode .gvy all
duti -s com.microsoft.VSCode .gsp all
duti -s com.microsoft.VSCode .cfg all
duti -s com.microsoft.VSCode .hcl all
duti -s com.microsoft.VSCode .nomad all
duti -s com.microsoft.VSCode .tf all
duti -s com.microsoft.VSCode .tfvars all
duti -s com.microsoft.VSCode .workflow all
duti -s com.microsoft.VSCode .hlsl all
duti -s com.microsoft.VSCode .cginc all
duti -s com.microsoft.VSCode .fx all
duti -s com.microsoft.VSCode .fxh all
duti -s com.microsoft.VSCode .hlsli all
duti -s com.microsoft.VSCode .hocon all
duti -s com.microsoft.VSCode .scalafix.conf all
duti -s com.microsoft.VSCode .scalafmt.conf all
duti -s com.microsoft.VSCode .html all
duti -s com.microsoft.VSCode .hta all
duti -s com.microsoft.VSCode .htm all
duti -s com.microsoft.VSCode .html.hl all
duti -s com.microsoft.VSCode .inc all
duti -s com.microsoft.VSCode .xht all
duti -s com.microsoft.VSCode .xhtml all
duti -s com.microsoft.VSCode .ecr all
duti -s com.microsoft.VSCode .eex all
duti -s com.microsoft.VSCode .html.heex all
duti -s com.microsoft.VSCode .html.leex all
duti -s com.microsoft.VSCode .erb all
duti -s com.microsoft.VSCode .erb.deface all
duti -s com.microsoft.VSCode .rhtml all
duti -s com.microsoft.VSCode .phtml all
duti -s com.microsoft.VSCode .cshtml all
duti -s com.microsoft.VSCode .razor all
duti -s com.microsoft.VSCode .http all
duti -s com.microsoft.VSCode .hxml all
duti -s com.microsoft.VSCode .hack all
duti -s com.microsoft.VSCode .hh all
duti -s com.microsoft.VSCode .hhi all
duti -s com.microsoft.VSCode .php all
duti -s com.microsoft.VSCode .haml all
duti -s com.microsoft.VSCode .haml.deface all
duti -s com.microsoft.VSCode .handlebars all
duti -s com.microsoft.VSCode .hbs all
duti -s com.microsoft.VSCode .hb all
duti -s com.microsoft.VSCode .hs all
duti -s com.microsoft.VSCode .hs-boot all
duti -s com.microsoft.VSCode .hsc all
duti -s com.microsoft.VSCode .hx all
duti -s com.microsoft.VSCode .hxsl all
duti -s com.microsoft.VSCode .q all
duti -s com.microsoft.VSCode .hql all
duti -s com.microsoft.VSCode .hc all
duti -s com.microsoft.VSCode .hy all
duti -s com.microsoft.VSCode .bf all
duti -s com.microsoft.VSCode .pro all
duti -s com.microsoft.VSCode .dlm all
duti -s com.microsoft.VSCode .ipf all
duti -s com.microsoft.VSCode .ini all
duti -s com.microsoft.VSCode .cfg all
duti -s com.microsoft.VSCode .cnf all
duti -s com.microsoft.VSCode .dof all
duti -s com.microsoft.VSCode .lektorproject all
duti -s com.microsoft.VSCode .prefs all
duti -s com.microsoft.VSCode .pro all
duti -s com.microsoft.VSCode .properties all
duti -s com.microsoft.VSCode .url all
duti -s com.microsoft.VSCode .coveragerc all
duti -s com.microsoft.VSCode .flake8 all
duti -s com.microsoft.VSCode .pylintrc all
duti -s com.microsoft.VSCode .irclog all
duti -s com.microsoft.VSCode .weechatlog all
duti -s com.microsoft.VSCode .idr all
duti -s com.microsoft.VSCode .lidr all
duti -s com.microsoft.VSCode .gitignore all
duti -s com.microsoft.VSCode .atomignore all
duti -s com.microsoft.VSCode .babelignore all
duti -s com.microsoft.VSCode .bzrignore all
duti -s com.microsoft.VSCode .coffeelintignore all
duti -s com.microsoft.VSCode .cvsignore all
duti -s com.microsoft.VSCode .dockerignore all
duti -s com.microsoft.VSCode .eleventyignore all
duti -s com.microsoft.VSCode .eslintignore all
duti -s com.microsoft.VSCode .gitignore all
duti -s com.microsoft.VSCode .markdownlintignore all
duti -s com.microsoft.VSCode .nodemonignore all
duti -s com.microsoft.VSCode .npmignore all
duti -s com.microsoft.VSCode .prettierignore all
duti -s com.microsoft.VSCode .stylelintignore all
duti -s com.microsoft.VSCode .vercelignore all
duti -s com.microsoft.VSCode .vscodeignore all
duti -s com.microsoft.VSCode .ijm all
duti -s com.microsoft.VSCode .imba all
duti -s com.microsoft.VSCode .ni all
duti -s com.microsoft.VSCode .i7x all
duti -s com.microsoft.VSCode .ink all
duti -s com.microsoft.VSCode .iss all
duti -s com.microsoft.VSCode .isl all
duti -s com.microsoft.VSCode .io all
duti -s com.microsoft.VSCode .ik all
duti -s com.microsoft.VSCode .thy all
duti -s com.microsoft.VSCode .ijs all
duti -s com.microsoft.VSCode .jcl all
duti -s com.microsoft.VSCode .flex all
duti -s com.microsoft.VSCode .jflex all
duti -s com.microsoft.VSCode .json all
duti -s com.microsoft.VSCode .4DForm all
duti -s com.microsoft.VSCode .4DProject all
duti -s com.microsoft.VSCode .avsc all
duti -s com.microsoft.VSCode .geojson all
duti -s com.microsoft.VSCode .gltf all
duti -s com.microsoft.VSCode .har all
duti -s com.microsoft.VSCode .ice all
duti -s com.microsoft.VSCode .JSON-tmLanguage all
duti -s com.microsoft.VSCode .jsonl all
duti -s com.microsoft.VSCode .mcmeta all
duti -s com.microsoft.VSCode .tfstate all
duti -s com.microsoft.VSCode .tfstate.backup all
duti -s com.microsoft.VSCode .topojson all
duti -s com.microsoft.VSCode .webapp all
duti -s com.microsoft.VSCode .webmanifest all
duti -s com.microsoft.VSCode .yy all
duti -s com.microsoft.VSCode .yyp all
duti -s com.microsoft.VSCode .all-contributorsrc all
duti -s com.microsoft.VSCode .arcconfig all
duti -s com.microsoft.VSCode .auto-changelog all
duti -s com.microsoft.VSCode .c8rc all
duti -s com.microsoft.VSCode .htmlhintrc all
duti -s com.microsoft.VSCode .imgbotconfig all
duti -s com.microsoft.VSCode .nycrc all
duti -s com.microsoft.VSCode .tern-config all
duti -s com.microsoft.VSCode .tern-project all
duti -s com.microsoft.VSCode .watchmanconfig all
duti -s com.microsoft.VSCode .jsonc all
duti -s com.microsoft.VSCode .code-snippets all
duti -s com.microsoft.VSCode .code-workspace all
duti -s com.microsoft.VSCode .sublime-build all
duti -s com.microsoft.VSCode .sublime-commands all
duti -s com.microsoft.VSCode .sublime-completions all
duti -s com.microsoft.VSCode .sublime-keymap all
duti -s com.microsoft.VSCode .sublime-macro all
duti -s com.microsoft.VSCode .sublime-menu all
duti -s com.microsoft.VSCode .sublime-mousemap all
duti -s com.microsoft.VSCode .sublime-project all
duti -s com.microsoft.VSCode .sublime-settings all
duti -s com.microsoft.VSCode .sublime-theme all
duti -s com.microsoft.VSCode .sublime-workspace all
duti -s com.microsoft.VSCode .sublime_metrics all
duti -s com.microsoft.VSCode .sublime_session all
duti -s com.microsoft.VSCode .babelrc all
duti -s com.microsoft.VSCode .devcontainer.json all
duti -s com.microsoft.VSCode .eslintrc.json all
duti -s com.microsoft.VSCode .jscsrc all
duti -s com.microsoft.VSCode .jshintrc all
duti -s com.microsoft.VSCode .jslintrc all
duti -s com.microsoft.VSCode .swcrc all
duti -s com.microsoft.VSCode .json5 all
duti -s com.microsoft.VSCode .jsonld all
duti -s com.microsoft.VSCode .jq all
duti -s com.microsoft.VSCode .janet all
duti -s com.microsoft.VSCode .j all
duti -s com.microsoft.VSCode .java all
duti -s com.microsoft.VSCode .jav all
duti -s com.microsoft.VSCode .jsh all
duti -s com.microsoft.VSCode .properties all
duti -s com.microsoft.VSCode .jsp all
duti -s com.microsoft.VSCode .tag all
duti -s com.microsoft.VSCode .js all
duti -s com.microsoft.VSCode ._js all
duti -s com.microsoft.VSCode .bones all
duti -s com.microsoft.VSCode .cjs all
duti -s com.microsoft.VSCode .es all
duti -s com.microsoft.VSCode .es6 all
duti -s com.microsoft.VSCode .frag all
duti -s com.microsoft.VSCode .gs all
duti -s com.microsoft.VSCode .jake all
duti -s com.microsoft.VSCode .javascript all
duti -s com.microsoft.VSCode .jsb all
duti -s com.microsoft.VSCode .jscad all
duti -s com.microsoft.VSCode .jsfl all
duti -s com.microsoft.VSCode .jslib all
duti -s com.microsoft.VSCode .jsm all
duti -s com.microsoft.VSCode .jspre all
duti -s com.microsoft.VSCode .jss all
duti -s com.microsoft.VSCode .jsx all
duti -s com.microsoft.VSCode .mjs all
duti -s com.microsoft.VSCode .njs all
duti -s com.microsoft.VSCode .pac all
duti -s com.microsoft.VSCode .sjs all
duti -s com.microsoft.VSCode .ssjs all
duti -s com.microsoft.VSCode .xsjs all
duti -s com.microsoft.VSCode .xsjslib all
duti -s com.microsoft.VSCode .js.erb all
duti -s com.microsoft.VSCode .snap all
duti -s com.microsoft.VSCode .mps all
duti -s com.microsoft.VSCode .mpl all
duti -s com.microsoft.VSCode .msd all
duti -s com.microsoft.VSCode .jinja all
duti -s com.microsoft.VSCode .j2 all
duti -s com.microsoft.VSCode .jinja2 all
duti -s com.microsoft.VSCode .jison all
duti -s com.microsoft.VSCode .jisonlex all
duti -s com.microsoft.VSCode .ol all
duti -s com.microsoft.VSCode .iol all
duti -s com.microsoft.VSCode .jsonnet all
duti -s com.microsoft.VSCode .libsonnet all
duti -s com.microsoft.VSCode .jl all
duti -s com.microsoft.VSCode .ipynb all
duti -s com.microsoft.VSCode .krl all
duti -s com.microsoft.VSCode .ksy all
duti -s com.microsoft.VSCode .kak all
duti -s com.microsoft.VSCode .ks all
duti -s com.microsoft.VSCode .kicad_pcb all
duti -s com.microsoft.VSCode .kicad_mod all
duti -s com.microsoft.VSCode .kicad_wks all
duti -s com.microsoft.VSCode .brd all
duti -s com.microsoft.VSCode .kicad_sch all
duti -s com.microsoft.VSCode .sch all
duti -s com.microsoft.VSCode .ks all
duti -s com.microsoft.VSCode .kit all
duti -s com.microsoft.VSCode .kt all
duti -s com.microsoft.VSCode .ktm all
duti -s com.microsoft.VSCode .kts all
duti -s com.microsoft.VSCode .csl all
duti -s com.microsoft.VSCode .kql all
duti -s com.microsoft.VSCode .lfe all
duti -s com.microsoft.VSCode .ll all
duti -s com.microsoft.VSCode .lol all
duti -s com.microsoft.VSCode .lsl all
duti -s com.microsoft.VSCode .lslp all
duti -s com.microsoft.VSCode .asy all
duti -s com.microsoft.VSCode .lvproj all
duti -s com.microsoft.VSCode .lvclass all
duti -s com.microsoft.VSCode .lvlib all
duti -s com.microsoft.VSCode .lark all
duti -s com.microsoft.VSCode .lasso all
duti -s com.microsoft.VSCode .las all
duti -s com.microsoft.VSCode .lasso8 all
duti -s com.microsoft.VSCode .lasso9 all
duti -s com.microsoft.VSCode .latte all
duti -s com.microsoft.VSCode .lean all
duti -s com.microsoft.VSCode .hlean all
duti -s com.microsoft.VSCode .lean all
duti -s com.microsoft.VSCode .less all
duti -s com.microsoft.VSCode .l all
duti -s com.microsoft.VSCode .lex all
duti -s com.microsoft.VSCode .ligo all
duti -s com.microsoft.VSCode .ly all
duti -s com.microsoft.VSCode .ily all
duti -s com.microsoft.VSCode .b all
duti -s com.microsoft.VSCode .m all
duti -s com.microsoft.VSCode .ld all
duti -s com.microsoft.VSCode .lds all
duti -s com.microsoft.VSCode .x all
duti -s com.microsoft.VSCode .mod all
duti -s com.microsoft.VSCode .liquid all
duti -s com.microsoft.VSCode .lagda all
duti -s com.microsoft.VSCode .litcoffee all
duti -s com.microsoft.VSCode .coffee.md all
duti -s com.microsoft.VSCode .lhs all
duti -s com.microsoft.VSCode .ls all
duti -s com.microsoft.VSCode ._ls all
duti -s com.microsoft.VSCode .xm all
duti -s com.microsoft.VSCode .x all
duti -s com.microsoft.VSCode .xi all
duti -s com.microsoft.VSCode .lgt all
duti -s com.microsoft.VSCode .logtalk all
duti -s com.microsoft.VSCode .lkml all
duti -s com.microsoft.VSCode .lookml all
duti -s com.microsoft.VSCode .ls all
duti -s com.microsoft.VSCode .lua all
duti -s com.microsoft.VSCode .fcgi all
duti -s com.microsoft.VSCode .nse all
duti -s com.microsoft.VSCode .p8 all
duti -s com.microsoft.VSCode .pd_lua all
duti -s com.microsoft.VSCode .rbxs all
duti -s com.microsoft.VSCode .rockspec all
duti -s com.microsoft.VSCode .wlua all
duti -s com.microsoft.VSCode .luacheckrc all
duti -s com.microsoft.VSCode .mumps all
duti -s com.microsoft.VSCode .m all
duti -s com.microsoft.VSCode .m4 all
duti -s com.microsoft.VSCode .mc all
duti -s com.microsoft.VSCode .m4 all
duti -s com.microsoft.VSCode .matlab all
duti -s com.microsoft.VSCode .m all
duti -s com.microsoft.VSCode .ms all
duti -s com.microsoft.VSCode .mcr all
duti -s com.microsoft.VSCode .mdx all
duti -s com.microsoft.VSCode .mlir all
duti -s com.microsoft.VSCode .mq4 all
duti -s com.microsoft.VSCode .mqh all
duti -s com.microsoft.VSCode .mq5 all
duti -s com.microsoft.VSCode .mqh all
duti -s com.microsoft.VSCode .mtml all
duti -s com.microsoft.VSCode .muf all
duti -s com.microsoft.VSCode .m all
duti -s com.microsoft.VSCode .m2 all
duti -s com.microsoft.VSCode .mak all
duti -s com.microsoft.VSCode .d all
duti -s com.microsoft.VSCode .make all
duti -s com.microsoft.VSCode .makefile all
duti -s com.microsoft.VSCode .mk all
duti -s com.microsoft.VSCode .mkfile all
duti -s com.microsoft.VSCode .mako all
duti -s com.microsoft.VSCode .mao all
duti -s com.microsoft.VSCode .md all
duti -s com.microsoft.VSCode .livemd all
duti -s com.microsoft.VSCode .markdown all
duti -s com.microsoft.VSCode .mdown all
duti -s com.microsoft.VSCode .mdwn all
duti -s com.microsoft.VSCode .mkd all
duti -s com.microsoft.VSCode .mkdn all
duti -s com.microsoft.VSCode .mkdown all
duti -s com.microsoft.VSCode .ronn all
duti -s com.microsoft.VSCode .scd all
duti -s com.microsoft.VSCode .workbook all
duti -s com.microsoft.VSCode .marko all
duti -s com.microsoft.VSCode .mask all
duti -s com.microsoft.VSCode .mathematica all
duti -s com.microsoft.VSCode .cdf all
duti -s com.microsoft.VSCode .m all
duti -s com.microsoft.VSCode .ma all
duti -s com.microsoft.VSCode .mt all
duti -s com.microsoft.VSCode .nb all
duti -s com.microsoft.VSCode .nbp all
duti -s com.microsoft.VSCode .wl all
duti -s com.microsoft.VSCode .wlt all
duti -s com.microsoft.VSCode .maxpat all
duti -s com.microsoft.VSCode .maxhelp all
duti -s com.microsoft.VSCode .maxproj all
duti -s com.microsoft.VSCode .mxt all
duti -s com.microsoft.VSCode .pat all
duti -s com.microsoft.VSCode .m all
duti -s com.microsoft.VSCode .moo all
duti -s com.microsoft.VSCode .mmd all
duti -s com.microsoft.VSCode .mermaid all
duti -s com.microsoft.VSCode .metal all
duti -s com.microsoft.VSCode .dsp all
duti -s com.microsoft.VSCode .sln all
duti -s com.microsoft.VSCode .minid all
duti -s com.microsoft.VSCode .yaml all
duti -s com.microsoft.VSCode .yml all
duti -s com.microsoft.VSCode .mint all
duti -s com.microsoft.VSCode .druby all
duti -s com.microsoft.VSCode .duby all
duti -s com.microsoft.VSCode .mirah all
duti -s com.microsoft.VSCode .mo all
duti -s com.microsoft.VSCode .mod all
duti -s com.microsoft.VSCode .i3 all
duti -s com.microsoft.VSCode .ig all
duti -s com.microsoft.VSCode .m3 all
duti -s com.microsoft.VSCode .mg all
duti -s com.microsoft.VSCode .mms all
duti -s com.microsoft.VSCode .mmk all
duti -s com.microsoft.VSCode .monkey all
duti -s com.microsoft.VSCode .monkey2 all
duti -s com.microsoft.VSCode .mc all
duti -s com.microsoft.VSCode .moo all
duti -s com.microsoft.VSCode .moon all
duti -s com.microsoft.VSCode .mo all
duti -s com.microsoft.VSCode .asm all
duti -s com.microsoft.VSCode .i all
duti -s com.microsoft.VSCode .inc all
duti -s com.microsoft.VSCode .s all
duti -s com.microsoft.VSCode .x68 all
duti -s com.microsoft.VSCode .move all
duti -s com.microsoft.VSCode .muse all
duti -s com.microsoft.VSCode .mustache all
duti -s com.microsoft.VSCode .myt all
duti -s com.microsoft.VSCode .nasl all
duti -s com.microsoft.VSCode .inc all
duti -s com.microsoft.VSCode .ncl all
duti -s com.microsoft.VSCode .neon all
duti -s com.microsoft.VSCode .nl all
duti -s com.microsoft.VSCode .npmrc all
duti -s com.microsoft.VSCode .nsi all
duti -s com.microsoft.VSCode .nsh all
duti -s com.microsoft.VSCode .nss all
duti -s com.microsoft.VSCode .nas all
duti -s com.microsoft.VSCode .ne all
duti -s com.microsoft.VSCode .nearley all
duti -s com.microsoft.VSCode .n all
duti -s com.microsoft.VSCode .axs all
duti -s com.microsoft.VSCode .axi all
duti -s com.microsoft.VSCode .axs.erb all
duti -s com.microsoft.VSCode .axi.erb all
duti -s com.microsoft.VSCode .nlogo all
duti -s com.microsoft.VSCode .nl all
duti -s com.microsoft.VSCode .lisp all
duti -s com.microsoft.VSCode .lsp all
duti -s com.microsoft.VSCode .nf all
duti -s com.microsoft.VSCode .nginx all
duti -s com.microsoft.VSCode .nginxconf all
duti -s com.microsoft.VSCode .vhost all
duti -s com.microsoft.VSCode .nim all
duti -s com.microsoft.VSCode .nim.cfg all
duti -s com.microsoft.VSCode .nimble all
duti -s com.microsoft.VSCode .nimrod all
duti -s com.microsoft.VSCode .nims all
duti -s com.microsoft.VSCode .ninja all
duti -s com.microsoft.VSCode .nit all
duti -s com.microsoft.VSCode .nix all
duti -s com.microsoft.VSCode .nu all
duti -s com.microsoft.VSCode .numpy all
duti -s com.microsoft.VSCode .numpyw all
duti -s com.microsoft.VSCode .numsc all
duti -s com.microsoft.VSCode .njk all
duti -s com.microsoft.VSCode .nu all
duti -s com.microsoft.VSCode .json all
duti -s com.microsoft.VSCode .yaml all
duti -s com.microsoft.VSCode .yml all
duti -s com.microsoft.VSCode .json all
duti -s com.microsoft.VSCode .yaml all
duti -s com.microsoft.VSCode .yml all
duti -s com.microsoft.VSCode .ml all
duti -s com.microsoft.VSCode .eliom all
duti -s com.microsoft.VSCode .eliomi all
duti -s com.microsoft.VSCode .ml4 all
duti -s com.microsoft.VSCode .mli all
duti -s com.microsoft.VSCode .mll all
duti -s com.microsoft.VSCode .mly all
duti -s com.microsoft.VSCode .objdump all
duti -s com.microsoft.VSCode .odin all
duti -s com.microsoft.VSCode .cls all
duti -s com.microsoft.VSCode .m all
duti -s com.microsoft.VSCode .h all
duti -s com.microsoft.VSCode .mm all
duti -s com.microsoft.VSCode .j all
duti -s com.microsoft.VSCode .sj all
duti -s com.microsoft.VSCode .odin all
duti -s com.microsoft.VSCode .omgrofl all
duti -s com.microsoft.VSCode .opa all
duti -s com.microsoft.VSCode .opal all
duti -s com.microsoft.VSCode .rego all
duti -s com.microsoft.VSCode .cl all
duti -s com.microsoft.VSCode .opencl all
duti -s com.microsoft.VSCode .p all
duti -s com.microsoft.VSCode .cls all
duti -s com.microsoft.VSCode .w all
duti -s com.microsoft.VSCode .qasm all
duti -s com.microsoft.VSCode .scad all
duti -s com.microsoft.VSCode .plist all
duti -s com.microsoft.VSCode .glyphs all
duti -s com.microsoft.VSCode .fea all
duti -s com.microsoft.VSCode .ackrc all
duti -s com.microsoft.VSCode .rspec all
duti -s com.microsoft.VSCode .yardopts all
duti -s com.microsoft.VSCode .org all
duti -s com.microsoft.VSCode .ox all
duti -s com.microsoft.VSCode .oxh all
duti -s com.microsoft.VSCode .oxo all
duti -s com.microsoft.VSCode .oxygene all
duti -s com.microsoft.VSCode .oz all
duti -s com.microsoft.VSCode .p4 all
duti -s com.microsoft.VSCode .pddl all
duti -s com.microsoft.VSCode .pegjs all
duti -s com.microsoft.VSCode .php all
duti -s com.microsoft.VSCode .aw all
duti -s com.microsoft.VSCode .ctp all
duti -s com.microsoft.VSCode .fcgi all
duti -s com.microsoft.VSCode .inc all
duti -s com.microsoft.VSCode .php3 all
duti -s com.microsoft.VSCode .php4 all
duti -s com.microsoft.VSCode .php5 all
duti -s com.microsoft.VSCode .phps all
duti -s com.microsoft.VSCode .phpt all
duti -s com.microsoft.VSCode .php all
duti -s com.microsoft.VSCode .php_cs all
duti -s com.microsoft.VSCode .php_cs.dist all
duti -s com.microsoft.VSCode .pls all
duti -s com.microsoft.VSCode .bdy all
duti -s com.microsoft.VSCode .ddl all
duti -s com.microsoft.VSCode .fnc all
duti -s com.microsoft.VSCode .pck all
duti -s com.microsoft.VSCode .pkb all
duti -s com.microsoft.VSCode .pks all
duti -s com.microsoft.VSCode .plb all
duti -s com.microsoft.VSCode .plsql all
duti -s com.microsoft.VSCode .prc all
duti -s com.microsoft.VSCode .spc all
duti -s com.microsoft.VSCode .sql all
duti -s com.microsoft.VSCode .tpb all
duti -s com.microsoft.VSCode .tps all
duti -s com.microsoft.VSCode .trg all
duti -s com.microsoft.VSCode .vw all
duti -s com.microsoft.VSCode .pgsql all
duti -s com.microsoft.VSCode .sql all
duti -s com.microsoft.VSCode .pov all
duti -s com.microsoft.VSCode .inc all
duti -s com.microsoft.VSCode .pact all
duti -s com.microsoft.VSCode .pan all
duti -s com.microsoft.VSCode .psc all
duti -s com.microsoft.VSCode .parrot all
duti -s com.microsoft.VSCode .pasm all
duti -s com.microsoft.VSCode .pir all
duti -s com.microsoft.VSCode .pas all
duti -s com.microsoft.VSCode .dfm all
duti -s com.microsoft.VSCode .dpr all
duti -s com.microsoft.VSCode .inc all
duti -s com.microsoft.VSCode .lpr all
duti -s com.microsoft.VSCode .pascal all
duti -s com.microsoft.VSCode .pp all
duti -s com.microsoft.VSCode .pwn all
duti -s com.microsoft.VSCode .inc all
duti -s com.microsoft.VSCode .sma all
duti -s com.microsoft.VSCode .pep all
duti -s com.microsoft.VSCode .pl all
duti -s com.microsoft.VSCode .al all
duti -s com.microsoft.VSCode .cgi all
duti -s com.microsoft.VSCode .fcgi all
duti -s com.microsoft.VSCode .perl all
duti -s com.microsoft.VSCode .ph all
duti -s com.microsoft.VSCode .plx all
duti -s com.microsoft.VSCode .pm all
duti -s com.microsoft.VSCode .psgi all
duti -s com.microsoft.VSCode .t all
duti -s com.microsoft.VSCode .latexmkrc all
duti -s com.microsoft.VSCode .pic all
duti -s com.microsoft.VSCode .chem all
duti -s com.microsoft.VSCode .pkl all
duti -s com.microsoft.VSCode .l all
duti -s com.microsoft.VSCode .pig all
duti -s com.microsoft.VSCode .pike all
duti -s com.microsoft.VSCode .pmod all
duti -s com.microsoft.VSCode .puml all
duti -s com.microsoft.VSCode .iuml all
duti -s com.microsoft.VSCode .plantuml all
duti -s com.microsoft.VSCode .pod all
duti -s com.microsoft.VSCode .pod all
duti -s com.microsoft.VSCode .pod6 all
duti -s com.microsoft.VSCode .pogo all
duti -s com.microsoft.VSCode .polar all
duti -s com.microsoft.VSCode .pony all
duti -s com.microsoft.VSCode .por all
duti -s com.microsoft.VSCode .pcss all
duti -s com.microsoft.VSCode .postcss all
duti -s com.microsoft.VSCode .ps all
duti -s com.microsoft.VSCode .eps all
duti -s com.microsoft.VSCode .epsi all
duti -s com.microsoft.VSCode .pfa all
duti -s com.microsoft.VSCode .pbt all
duti -s com.microsoft.VSCode .sra all
duti -s com.microsoft.VSCode .sru all
duti -s com.microsoft.VSCode .srw all
duti -s com.microsoft.VSCode .ps1 all
duti -s com.microsoft.VSCode .psd1 all
duti -s com.microsoft.VSCode .psm1 all
duti -s com.microsoft.VSCode .praat all
duti -s com.microsoft.VSCode .prisma all
duti -s com.microsoft.VSCode .pde all
duti -s com.microsoft.VSCode .pro all
duti -s com.microsoft.VSCode .pl all
duti -s com.microsoft.VSCode .plt all
duti -s com.microsoft.VSCode .pro all
duti -s com.microsoft.VSCode .prolog all
duti -s com.microsoft.VSCode .yap all
duti -s com.microsoft.VSCode .pml all
duti -s com.microsoft.VSCode .spin all
duti -s com.microsoft.VSCode .proto all
duti -s com.microsoft.VSCode .textproto all
duti -s com.microsoft.VSCode .pbt all
duti -s com.microsoft.VSCode .pbtxt all
duti -s com.microsoft.VSCode .asc all
duti -s com.microsoft.VSCode .pub all
duti -s com.microsoft.VSCode .jade all
duti -s com.microsoft.VSCode .pug all
duti -s com.microsoft.VSCode .pp all
duti -s com.microsoft.VSCode .pd all
duti -s com.microsoft.VSCode .pb all
duti -s com.microsoft.VSCode .pbi all
duti -s com.microsoft.VSCode .purs all
duti -s com.microsoft.VSCode .arr all
duti -s com.microsoft.VSCode .py all
duti -s com.microsoft.VSCode .cgi all
duti -s com.microsoft.VSCode .fcgi all
duti -s com.microsoft.VSCode .gyp all
duti -s com.microsoft.VSCode .gypi all
duti -s com.microsoft.VSCode .lmi all
duti -s com.microsoft.VSCode .py3 all
duti -s com.microsoft.VSCode .pyde all
duti -s com.microsoft.VSCode .pyi all
duti -s com.microsoft.VSCode .pyp all
duti -s com.microsoft.VSCode .pyt all
duti -s com.microsoft.VSCode .pyw all
duti -s com.microsoft.VSCode .rpy all
duti -s com.microsoft.VSCode .spec all
duti -s com.microsoft.VSCode .tac all
duti -s com.microsoft.VSCode .wsgi all
duti -s com.microsoft.VSCode .xpy all
duti -s com.microsoft.VSCode .gclient all
duti -s com.microsoft.VSCode .pytb all
duti -s com.microsoft.VSCode .qs all
duti -s com.microsoft.VSCode .qml all
duti -s com.microsoft.VSCode .qbs all
duti -s com.microsoft.VSCode .pro all
duti -s com.microsoft.VSCode .pri all
duti -s com.microsoft.VSCode .qs all
duti -s com.microsoft.VSCode .r all
duti -s com.microsoft.VSCode .rd all
duti -s com.microsoft.VSCode .rsx all
duti -s com.microsoft.VSCode .Rprofile all
duti -s com.microsoft.VSCode .raml all
duti -s com.microsoft.VSCode .rbs all
duti -s com.microsoft.VSCode .rdoc all
duti -s com.microsoft.VSCode .rbbas all
duti -s com.microsoft.VSCode .rbfrm all
duti -s com.microsoft.VSCode .rbmnu all
duti -s com.microsoft.VSCode .rbres all
duti -s com.microsoft.VSCode .rbtbar all
duti -s com.microsoft.VSCode .rbuistate all
duti -s com.microsoft.VSCode .rexx all
duti -s com.microsoft.VSCode .pprx all
duti -s com.microsoft.VSCode .rex all
duti -s com.microsoft.VSCode .qmd all
duti -s com.microsoft.VSCode .rmd all
duti -s com.microsoft.VSCode .x all
duti -s com.microsoft.VSCode .rpgle all
duti -s com.microsoft.VSCode .sqlrpgle all
duti -s com.microsoft.VSCode .spec all
duti -s com.microsoft.VSCode .rnh all
duti -s com.microsoft.VSCode .rno all
duti -s com.microsoft.VSCode .rkt all
duti -s com.microsoft.VSCode .rktd all
duti -s com.microsoft.VSCode .rktl all
duti -s com.microsoft.VSCode .scrbl all
duti -s com.microsoft.VSCode .rl all
duti -s com.microsoft.VSCode .6pl all
duti -s com.microsoft.VSCode .6pm all
duti -s com.microsoft.VSCode .nqp all
duti -s com.microsoft.VSCode .p6 all
duti -s com.microsoft.VSCode .p6l all
duti -s com.microsoft.VSCode .p6m all
duti -s com.microsoft.VSCode .pl all
duti -s com.microsoft.VSCode .pl6 all
duti -s com.microsoft.VSCode .pm all
duti -s com.microsoft.VSCode .pm6 all
duti -s com.microsoft.VSCode .raku all
duti -s com.microsoft.VSCode .rakumod all
duti -s com.microsoft.VSCode .t all
duti -s com.microsoft.VSCode .rsc all
duti -s com.microsoft.VSCode .raw all
duti -s com.microsoft.VSCode .res all
duti -s com.microsoft.VSCode .inputrc all
duti -s com.microsoft.VSCode .re all
duti -s com.microsoft.VSCode .rei all
duti -s com.microsoft.VSCode .religo all
duti -s com.microsoft.VSCode .reb all
duti -s com.microsoft.VSCode .r all
duti -s com.microsoft.VSCode .r2 all
duti -s com.microsoft.VSCode .r3 all
duti -s com.microsoft.VSCode .rebol all
duti -s com.microsoft.VSCode .red all
duti -s com.microsoft.VSCode .reds all
duti -s com.microsoft.VSCode .cw all
duti -s com.microsoft.VSCode .regexp all
duti -s com.microsoft.VSCode .regex all
duti -s com.microsoft.VSCode .rpy all
duti -s com.microsoft.VSCode .rs all
duti -s com.microsoft.VSCode .rsh all
duti -s com.microsoft.VSCode .r all
duti -s com.microsoft.VSCode .rtf all
duti -s com.microsoft.VSCode .ring all
duti -s com.microsoft.VSCode .riot all
duti -s com.microsoft.VSCode .robot all
duti -s com.microsoft.VSCode .roff all
duti -s com.microsoft.VSCode .1 all
duti -s com.microsoft.VSCode .1in all
duti -s com.microsoft.VSCode .1m all
duti -s com.microsoft.VSCode .1x all
duti -s com.microsoft.VSCode .2 all
duti -s com.microsoft.VSCode .3 all
duti -s com.microsoft.VSCode .3in all
duti -s com.microsoft.VSCode .3m all
duti -s com.microsoft.VSCode .3p all
duti -s com.microsoft.VSCode .3pm all
duti -s com.microsoft.VSCode .3qt all
duti -s com.microsoft.VSCode .3x all
duti -s com.microsoft.VSCode .4 all
duti -s com.microsoft.VSCode .5 all
duti -s com.microsoft.VSCode .6 all
duti -s com.microsoft.VSCode .7 all
duti -s com.microsoft.VSCode .8 all
duti -s com.microsoft.VSCode .9 all
duti -s com.microsoft.VSCode .l all
duti -s com.microsoft.VSCode .man all
duti -s com.microsoft.VSCode .mdoc all
duti -s com.microsoft.VSCode .me all
duti -s com.microsoft.VSCode .ms all
duti -s com.microsoft.VSCode .n all
duti -s com.microsoft.VSCode .nr all
duti -s com.microsoft.VSCode .rno all
duti -s com.microsoft.VSCode .tmac all
duti -s com.microsoft.VSCode .1 all
duti -s com.microsoft.VSCode .1in all
duti -s com.microsoft.VSCode .1m all
duti -s com.microsoft.VSCode .1x all
duti -s com.microsoft.VSCode .2 all
duti -s com.microsoft.VSCode .3 all
duti -s com.microsoft.VSCode .3in all
duti -s com.microsoft.VSCode .3m all
duti -s com.microsoft.VSCode .3p all
duti -s com.microsoft.VSCode .3pm all
duti -s com.microsoft.VSCode .3qt all
duti -s com.microsoft.VSCode .3x all
duti -s com.microsoft.VSCode .4 all
duti -s com.microsoft.VSCode .5 all
duti -s com.microsoft.VSCode .6 all
duti -s com.microsoft.VSCode .7 all
duti -s com.microsoft.VSCode .8 all
duti -s com.microsoft.VSCode .9 all
duti -s com.microsoft.VSCode .man all
duti -s com.microsoft.VSCode .mdoc all
duti -s com.microsoft.VSCode .rg all
duti -s com.microsoft.VSCode .rsc all
duti -s com.microsoft.VSCode .rb all
duti -s com.microsoft.VSCode .builder all
duti -s com.microsoft.VSCode .eye all
duti -s com.microsoft.VSCode .fcgi all
duti -s com.microsoft.VSCode .gemspec all
duti -s com.microsoft.VSCode .god all
duti -s com.microsoft.VSCode .jbuilder all
duti -s com.microsoft.VSCode .mspec all
duti -s com.microsoft.VSCode .pluginspec all
duti -s com.microsoft.VSCode .podspec all
duti -s com.microsoft.VSCode .prawn all
duti -s com.microsoft.VSCode .rabl all
duti -s com.microsoft.VSCode .rake all
duti -s com.microsoft.VSCode .rbi all
duti -s com.microsoft.VSCode .rbuild all
duti -s com.microsoft.VSCode .rbw all
duti -s com.microsoft.VSCode .rbx all
duti -s com.microsoft.VSCode .ru all
duti -s com.microsoft.VSCode .ruby all
duti -s com.microsoft.VSCode .spec all
duti -s com.microsoft.VSCode .thor all
duti -s com.microsoft.VSCode .watchr all
duti -s com.microsoft.VSCode .irbrc all
duti -s com.microsoft.VSCode .pryrc all
duti -s com.microsoft.VSCode .simplecov all
duti -s com.microsoft.VSCode .rs all
duti -s com.microsoft.VSCode .rs.in all
duti -s com.microsoft.VSCode .sas all
duti -s com.microsoft.VSCode .scss all
duti -s com.microsoft.VSCode .te all
duti -s com.microsoft.VSCode .smt2 all
duti -s com.microsoft.VSCode .smt all
duti -s com.microsoft.VSCode .sparql all
duti -s com.microsoft.VSCode .rq all
duti -s com.microsoft.VSCode .sqf all
duti -s com.microsoft.VSCode .hqf all
duti -s com.microsoft.VSCode .sql all
duti -s com.microsoft.VSCode .cql all
duti -s com.microsoft.VSCode .ddl all
duti -s com.microsoft.VSCode .inc all
duti -s com.microsoft.VSCode .mysql all
duti -s com.microsoft.VSCode .prc all
duti -s com.microsoft.VSCode .tab all
duti -s com.microsoft.VSCode .udf all
duti -s com.microsoft.VSCode .viw all
duti -s com.microsoft.VSCode .sql all
duti -s com.microsoft.VSCode .db2 all
duti -s com.microsoft.VSCode .srt all
duti -s com.microsoft.VSCode .star all
duti -s com.microsoft.VSCode .stl all
duti -s com.microsoft.VSCode .ston all
duti -s com.microsoft.VSCode .svg all
duti -s com.microsoft.VSCode .i all
duti -s com.microsoft.VSCode .sage all
duti -s com.microsoft.VSCode .sagews all
duti -s com.microsoft.VSCode .sls all
duti -s com.microsoft.VSCode .sass all
duti -s com.microsoft.VSCode .scala all
duti -s com.microsoft.VSCode .kojo all
duti -s com.microsoft.VSCode .sbt all
duti -s com.microsoft.VSCode .sc all
duti -s com.microsoft.VSCode .scaml all
duti -s com.microsoft.VSCode .scenic all
duti -s com.microsoft.VSCode .scm all
duti -s com.microsoft.VSCode .sch all
duti -s com.microsoft.VSCode .sld all
duti -s com.microsoft.VSCode .sls all
duti -s com.microsoft.VSCode .sps all
duti -s com.microsoft.VSCode .ss all
duti -s com.microsoft.VSCode .sci all
duti -s com.microsoft.VSCode .sce all
duti -s com.microsoft.VSCode .tst all
duti -s com.microsoft.VSCode .self all
duti -s com.microsoft.VSCode .shader all
duti -s com.microsoft.VSCode .sh all
duti -s com.microsoft.VSCode .bash all
duti -s com.microsoft.VSCode .bats all
duti -s com.microsoft.VSCode .cgi all
duti -s com.microsoft.VSCode .command all
duti -s com.microsoft.VSCode .fcgi all
duti -s com.microsoft.VSCode .ksh all
duti -s com.microsoft.VSCode .sh.in all
duti -s com.microsoft.VSCode .tmux all
duti -s com.microsoft.VSCode .tool all
duti -s com.microsoft.VSCode .trigger all
duti -s com.microsoft.VSCode .zsh all
duti -s com.microsoft.VSCode .zsh-theme all
duti -s com.microsoft.VSCode .bash_aliases all
duti -s com.microsoft.VSCode .bash_functions all
duti -s com.microsoft.VSCode .bash_history all
duti -s com.microsoft.VSCode .bash_logout all
duti -s com.microsoft.VSCode .bash_profile all
duti -s com.microsoft.VSCode .bashrc all
duti -s com.microsoft.VSCode .cshrc all
duti -s com.microsoft.VSCode .flaskenv all
duti -s com.microsoft.VSCode .kshrc all
duti -s com.microsoft.VSCode .login all
duti -s com.microsoft.VSCode .profile all
duti -s com.microsoft.VSCode .zlogin all
duti -s com.microsoft.VSCode .zlogout all
duti -s com.microsoft.VSCode .zprofile all
duti -s com.microsoft.VSCode .zshenv all
duti -s com.microsoft.VSCode .zshrc all
duti -s com.microsoft.VSCode .shellcheckrc all
duti -s com.microsoft.VSCode .sh-session all
duti -s com.microsoft.VSCode .shen all
duti -s com.microsoft.VSCode .sieve all
duti -s com.microsoft.VSCode .sfv all
duti -s com.microsoft.VSCode .sl all
duti -s com.microsoft.VSCode .ice all
duti -s com.microsoft.VSCode .slim all
duti -s com.microsoft.VSCode .cocci all
duti -s com.microsoft.VSCode .smali all
duti -s com.microsoft.VSCode .st all
duti -s com.microsoft.VSCode .cs all
duti -s com.microsoft.VSCode .tpl all
duti -s com.microsoft.VSCode .smithy all
duti -s com.microsoft.VSCode .smk all
duti -s com.microsoft.VSCode .snakefile all
duti -s com.microsoft.VSCode .sol all
duti -s com.microsoft.VSCode .sp all
duti -s com.microsoft.VSCode .inc all
duti -s com.microsoft.VSCode .sfd all
duti -s com.microsoft.VSCode .nut all
duti -s com.microsoft.VSCode .stan all
duti -s com.microsoft.VSCode .ml all
duti -s com.microsoft.VSCode .fun all
duti -s com.microsoft.VSCode .sig all
duti -s com.microsoft.VSCode .sml all
duti -s com.microsoft.VSCode .bzl all
duti -s com.microsoft.VSCode .star all
duti -s com.microsoft.VSCode .do all
duti -s com.microsoft.VSCode .ado all
duti -s com.microsoft.VSCode .doh all
duti -s com.microsoft.VSCode .ihlp all
duti -s com.microsoft.VSCode .mata all
duti -s com.microsoft.VSCode .matah all
duti -s com.microsoft.VSCode .sthlp all
duti -s com.microsoft.VSCode .st all
duti -s com.microsoft.VSCode .styl all
duti -s com.microsoft.VSCode .srt all
duti -s com.microsoft.VSCode .sss all
duti -s com.microsoft.VSCode .sc all
duti -s com.microsoft.VSCode .scd all
duti -s com.microsoft.VSCode .svelte all
duti -s com.microsoft.VSCode .sw all
duti -s com.microsoft.VSCode .rnw all
duti -s com.microsoft.VSCode .swift all
duti -s com.microsoft.VSCode .sv all
duti -s com.microsoft.VSCode .svh all
duti -s com.microsoft.VSCode .vh all
duti -s com.microsoft.VSCode .8xp all
duti -s com.microsoft.VSCode .8xk all
duti -s com.microsoft.VSCode .8xk.txt all
duti -s com.microsoft.VSCode .8xp.txt all
duti -s com.microsoft.VSCode .tlv all
duti -s com.microsoft.VSCode .tla all
duti -s com.microsoft.VSCode .toml all
duti -s com.microsoft.VSCode .sql all
duti -s com.microsoft.VSCode .tsv all
duti -s com.microsoft.VSCode .tsx all
duti -s com.microsoft.VSCode .txl all
duti -s com.microsoft.VSCode .talon all
duti -s com.microsoft.VSCode .tcl all
duti -s com.microsoft.VSCode .adp all
duti -s com.microsoft.VSCode .sdc all
duti -s com.microsoft.VSCode .tcl.in all
duti -s com.microsoft.VSCode .tm all
duti -s com.microsoft.VSCode .xdc all
duti -s com.microsoft.VSCode .tcsh all
duti -s com.microsoft.VSCode .csh all
duti -s com.microsoft.VSCode .tex all
duti -s com.microsoft.VSCode .aux all
duti -s com.microsoft.VSCode .bbx all
duti -s com.microsoft.VSCode .cbx all
duti -s com.microsoft.VSCode .cls all
duti -s com.microsoft.VSCode .dtx all
duti -s com.microsoft.VSCode .ins all
duti -s com.microsoft.VSCode .lbx all
duti -s com.microsoft.VSCode .ltx all
duti -s com.microsoft.VSCode .mkii all
duti -s com.microsoft.VSCode .mkiv all
duti -s com.microsoft.VSCode .mkvi all
duti -s com.microsoft.VSCode .sty all
duti -s com.microsoft.VSCode .toc all
duti -s com.microsoft.VSCode .tea all
duti -s com.microsoft.VSCode .t all
duti -s com.microsoft.VSCode .tftpl all
duti -s com.microsoft.VSCode .texinfo all
duti -s com.microsoft.VSCode .texi all
duti -s com.microsoft.VSCode .txi all
duti -s com.microsoft.VSCode .txt all
duti -s com.microsoft.VSCode .fr all
duti -s com.microsoft.VSCode .nb all
duti -s com.microsoft.VSCode .ncl all
duti -s com.microsoft.VSCode .no all
duti -s com.microsoft.VSCode .tm_properties all
duti -s com.microsoft.VSCode .textile all
duti -s com.microsoft.VSCode .thrift all
duti -s com.microsoft.VSCode .toit all
duti -s com.microsoft.VSCode .t all
duti -s com.microsoft.VSCode .tu all
duti -s com.microsoft.VSCode .ttl all
duti -s com.microsoft.VSCode .twig all
duti -s com.microsoft.VSCode .tl all
duti -s com.microsoft.VSCode .ts all
duti -s com.microsoft.VSCode .cts all
duti -s com.microsoft.VSCode .mts all
duti -s com.microsoft.VSCode .typ all
duti -s com.microsoft.VSCode .upc all
duti -s com.microsoft.VSCode .anim all
duti -s com.microsoft.VSCode .asset all
duti -s com.microsoft.VSCode .mask all
duti -s com.microsoft.VSCode .mat all
duti -s com.microsoft.VSCode .meta all
duti -s com.microsoft.VSCode .prefab all
duti -s com.microsoft.VSCode .unity all
duti -s com.microsoft.VSCode .s all
duti -s com.microsoft.VSCode .ms all
duti -s com.microsoft.VSCode .uno all
duti -s com.microsoft.VSCode .uc all
duti -s com.microsoft.VSCode .ur all
duti -s com.microsoft.VSCode .urs all
duti -s com.microsoft.VSCode .v all
duti -s com.microsoft.VSCode .bas all
duti -s com.microsoft.VSCode .cls all
duti -s com.microsoft.VSCode .frm all
duti -s com.microsoft.VSCode .vba all
duti -s com.microsoft.VSCode .vbs all
duti -s com.microsoft.VSCode .vcl all
duti -s com.microsoft.VSCode .vhdl all
duti -s com.microsoft.VSCode .vhd all
duti -s com.microsoft.VSCode .vhf all
duti -s com.microsoft.VSCode .vhi all
duti -s com.microsoft.VSCode .vho all
duti -s com.microsoft.VSCode .vhs all
duti -s com.microsoft.VSCode .vht all
duti -s com.microsoft.VSCode .vhw all
duti -s com.microsoft.VSCode .vala all
duti -s com.microsoft.VSCode .vapi all
duti -s com.microsoft.VSCode .vdf all
duti -s com.microsoft.VSCode .vtl all
duti -s com.microsoft.VSCode .v all
duti -s com.microsoft.VSCode .veo all
duti -s com.microsoft.VSCode .txt all
duti -s com.microsoft.VSCode .vim all
duti -s com.microsoft.VSCode .vba all
duti -s com.microsoft.VSCode .vimrc all
duti -s com.microsoft.VSCode .vmb all
duti -s com.microsoft.VSCode .exrc all
duti -s com.microsoft.VSCode .gvimrc all
duti -s com.microsoft.VSCode .nvimrc all
duti -s com.microsoft.VSCode .vimrc all
duti -s com.microsoft.VSCode .snip all
duti -s com.microsoft.VSCode .snippet all
duti -s com.microsoft.VSCode .snippets all
duti -s com.microsoft.VSCode .vb all
duti -s com.microsoft.VSCode .vbhtml all
duti -s com.microsoft.VSCode .bas all
duti -s com.microsoft.VSCode .cls all
duti -s com.microsoft.VSCode .ctl all
duti -s com.microsoft.VSCode .Dsr all
duti -s com.microsoft.VSCode .frm all
duti -s com.microsoft.VSCode .volt all
duti -s com.microsoft.VSCode .vue all
duti -s com.microsoft.VSCode .vy all
duti -s com.microsoft.VSCode .wdl all
duti -s com.microsoft.VSCode .wgsl all
duti -s com.microsoft.VSCode .mtl all
duti -s com.microsoft.VSCode .obj all
duti -s com.microsoft.VSCode .owl all
duti -s com.microsoft.VSCode .wast all
duti -s com.microsoft.VSCode .wat all
duti -s com.microsoft.VSCode .wit all
duti -s com.microsoft.VSCode .webidl all
duti -s com.microsoft.VSCode .vtt all
duti -s com.microsoft.VSCode .wgetrc all
duti -s com.microsoft.VSCode .whiley all
duti -s com.microsoft.VSCode .mediawiki all
duti -s com.microsoft.VSCode .wiki all
duti -s com.microsoft.VSCode .wikitext all
duti -s com.microsoft.VSCode .mc all
duti -s com.microsoft.VSCode .reg all
duti -s com.microsoft.VSCode .ws all
duti -s com.microsoft.VSCode .wlk all
duti -s com.microsoft.VSCode .toc all
duti -s com.microsoft.VSCode .wren all
duti -s com.microsoft.VSCode .xbm all
duti -s com.microsoft.VSCode .xpm all
duti -s com.microsoft.VSCode .pm all
duti -s com.microsoft.VSCode .x10 all
duti -s com.microsoft.VSCode .xc all
duti -s com.microsoft.VSCode .XCompose all
duti -s com.microsoft.VSCode .xml all
duti -s com.microsoft.VSCode .adml all
duti -s com.microsoft.VSCode .admx all
duti -s com.microsoft.VSCode .ant all
duti -s com.microsoft.VSCode .axaml all
duti -s com.microsoft.VSCode .axml all
duti -s com.microsoft.VSCode .builds all
duti -s com.microsoft.VSCode .ccproj all
duti -s com.microsoft.VSCode .ccxml all
duti -s com.microsoft.VSCode .clixml all
duti -s com.microsoft.VSCode .cproject all
duti -s com.microsoft.VSCode .cscfg all
duti -s com.microsoft.VSCode .csdef all
duti -s com.microsoft.VSCode .csl all
duti -s com.microsoft.VSCode .csproj all
duti -s com.microsoft.VSCode .ct all
duti -s com.microsoft.VSCode .depproj all
duti -s com.microsoft.VSCode .dita all
duti -s com.microsoft.VSCode .ditamap all
duti -s com.microsoft.VSCode .ditaval all
duti -s com.microsoft.VSCode .dll.config all
duti -s com.microsoft.VSCode .dotsettings all
duti -s com.microsoft.VSCode .filters all
duti -s com.microsoft.VSCode .fsproj all
duti -s com.microsoft.VSCode .fxml all
duti -s com.microsoft.VSCode .glade all
duti -s com.microsoft.VSCode .gml all
duti -s com.microsoft.VSCode .gmx all
duti -s com.microsoft.VSCode .grxml all
duti -s com.microsoft.VSCode .gst all
duti -s com.microsoft.VSCode .hzp all
duti -s com.microsoft.VSCode .iml all
duti -s com.microsoft.VSCode .ivy all
duti -s com.microsoft.VSCode .jelly all
duti -s com.microsoft.VSCode .jsproj all
duti -s com.microsoft.VSCode .kml all
duti -s com.microsoft.VSCode .launch all
duti -s com.microsoft.VSCode .mdpolicy all
duti -s com.microsoft.VSCode .mjml all
duti -s com.microsoft.VSCode .mm all
duti -s com.microsoft.VSCode .mod all
duti -s com.microsoft.VSCode .mxml all
duti -s com.microsoft.VSCode .natvis all
duti -s com.microsoft.VSCode .ncl all
duti -s com.microsoft.VSCode .ndproj all
duti -s com.microsoft.VSCode .nproj all
duti -s com.microsoft.VSCode .nuspec all
duti -s com.microsoft.VSCode .odd all
duti -s com.microsoft.VSCode .osm all
duti -s com.microsoft.VSCode .pkgproj all
duti -s com.microsoft.VSCode .pluginspec all
duti -s com.microsoft.VSCode .proj all
duti -s com.microsoft.VSCode .props all
duti -s com.microsoft.VSCode .ps1xml all
duti -s com.microsoft.VSCode .psc1 all
duti -s com.microsoft.VSCode .pt all
duti -s com.microsoft.VSCode .qhelp all
duti -s com.microsoft.VSCode .rdf all
duti -s com.microsoft.VSCode .res all
duti -s com.microsoft.VSCode .resx all
duti -s com.microsoft.VSCode .rs all
duti -s com.microsoft.VSCode .rss all
duti -s com.microsoft.VSCode .sch all
duti -s com.microsoft.VSCode .scxml all
duti -s com.microsoft.VSCode .sfproj all
duti -s com.microsoft.VSCode .shproj all
duti -s com.microsoft.VSCode .srdf all
duti -s com.microsoft.VSCode .storyboard all
duti -s com.microsoft.VSCode .sublime-snippet all
duti -s com.microsoft.VSCode .sw all
duti -s com.microsoft.VSCode .targets all
duti -s com.microsoft.VSCode .tml all
duti -s com.microsoft.VSCode .ts all
duti -s com.microsoft.VSCode .tsx all
duti -s com.microsoft.VSCode .typ all
duti -s com.microsoft.VSCode .ui all
duti -s com.microsoft.VSCode .urdf all
duti -s com.microsoft.VSCode .ux all
duti -s com.microsoft.VSCode .vbproj all
duti -s com.microsoft.VSCode .vcxproj all
duti -s com.microsoft.VSCode .vsixmanifest all
duti -s com.microsoft.VSCode .vssettings all
duti -s com.microsoft.VSCode .vstemplate all
duti -s com.microsoft.VSCode .vxml all
duti -s com.microsoft.VSCode .wixproj all
duti -s com.microsoft.VSCode .workflow all
duti -s com.microsoft.VSCode .wsdl all
duti -s com.microsoft.VSCode .wsf all
duti -s com.microsoft.VSCode .wxi all
duti -s com.microsoft.VSCode .wxl all
duti -s com.microsoft.VSCode .wxs all
duti -s com.microsoft.VSCode .x3d all
duti -s com.microsoft.VSCode .xacro all
duti -s com.microsoft.VSCode .xaml all
duti -s com.microsoft.VSCode .xib all
duti -s com.microsoft.VSCode .xlf all
duti -s com.microsoft.VSCode .xliff all
duti -s com.microsoft.VSCode .xmi all
duti -s com.microsoft.VSCode .xml.dist all
duti -s com.microsoft.VSCode .xmp all
duti -s com.microsoft.VSCode .xproj all
duti -s com.microsoft.VSCode .xsd all
duti -s com.microsoft.VSCode .xspec all
duti -s com.microsoft.VSCode .xul all
duti -s com.microsoft.VSCode .zcml all
duti -s com.microsoft.VSCode .classpath all
duti -s com.microsoft.VSCode .cproject all
duti -s com.microsoft.VSCode .project all
duti -s com.microsoft.VSCode .plist all
duti -s com.microsoft.VSCode .stTheme all
duti -s com.microsoft.VSCode .tmCommand all
duti -s com.microsoft.VSCode .tmLanguage all
duti -s com.microsoft.VSCode .tmPreferences all
duti -s com.microsoft.VSCode .tmSnippet all
duti -s com.microsoft.VSCode .tmTheme all
duti -s com.microsoft.VSCode .xsp-config all
duti -s com.microsoft.VSCode .xsp.metadata all
duti -s com.microsoft.VSCode .xpl all
duti -s com.microsoft.VSCode .xproc all
duti -s com.microsoft.VSCode .xquery all
duti -s com.microsoft.VSCode .xq all
duti -s com.microsoft.VSCode .xql all
duti -s com.microsoft.VSCode .xqm all
duti -s com.microsoft.VSCode .xqy all
duti -s com.microsoft.VSCode .xs all
duti -s com.microsoft.VSCode .xslt all
duti -s com.microsoft.VSCode .xsl all
duti -s com.microsoft.VSCode .xojo_code all
duti -s com.microsoft.VSCode .xojo_menu all
duti -s com.microsoft.VSCode .xojo_report all
duti -s com.microsoft.VSCode .xojo_script all
duti -s com.microsoft.VSCode .xojo_toolbar all
duti -s com.microsoft.VSCode .xojo_window all
duti -s com.microsoft.VSCode .xsh all
duti -s com.microsoft.VSCode .xtend all
duti -s com.microsoft.VSCode .yml all
duti -s com.microsoft.VSCode .mir all
duti -s com.microsoft.VSCode .reek all
duti -s com.microsoft.VSCode .rviz all
duti -s com.microsoft.VSCode .sublime-syntax all
duti -s com.microsoft.VSCode .syntax all
duti -s com.microsoft.VSCode .yaml all
duti -s com.microsoft.VSCode .yaml-tmlanguage all
duti -s com.microsoft.VSCode .yaml.sed all
duti -s com.microsoft.VSCode .yml.mysql all
duti -s com.microsoft.VSCode .clang-format all
duti -s com.microsoft.VSCode .clang-tidy all
duti -s com.microsoft.VSCode .gemrc all
duti -s com.microsoft.VSCode .yang all
duti -s com.microsoft.VSCode .yar all
duti -s com.microsoft.VSCode .yara all
duti -s com.microsoft.VSCode .yasnippet all
duti -s com.microsoft.VSCode .y all
duti -s com.microsoft.VSCode .yacc all
duti -s com.microsoft.VSCode .yy all
duti -s com.microsoft.VSCode .yul all
duti -s com.microsoft.VSCode .zap all
duti -s com.microsoft.VSCode .xzap all
duti -s com.microsoft.VSCode .zil all
duti -s com.microsoft.VSCode .mud all
duti -s com.microsoft.VSCode .zeek all
duti -s com.microsoft.VSCode .bro all
duti -s com.microsoft.VSCode .zs all
duti -s com.microsoft.VSCode .zep all
duti -s com.microsoft.VSCode .zig all
duti -s com.microsoft.VSCode .zimpl all
duti -s com.microsoft.VSCode .zmpl all
duti -s com.microsoft.VSCode .zpl all
duti -s com.microsoft.VSCode .curlrc all
duti -s com.microsoft.VSCode .desktop all
duti -s com.microsoft.VSCode .desktop.in all
duti -s com.microsoft.VSCode .service all
duti -s com.microsoft.VSCode .dircolors all
duti -s com.microsoft.VSCode .dir_colors all
duti -s com.microsoft.VSCode .dircolors all
duti -s com.microsoft.VSCode .ec all
duti -s com.microsoft.VSCode .eh all
duti -s com.microsoft.VSCode .edn all
duti -s com.microsoft.VSCode .fish all
duti -s com.microsoft.VSCode .hoon all
duti -s com.microsoft.VSCode .jq all
duti -s com.microsoft.VSCode .kv all
duti -s com.microsoft.VSCode .mrc all
duti -s com.microsoft.VSCode .mcfunction all
duti -s com.microsoft.VSCode .mu all
duti -s com.microsoft.VSCode .nanorc all
duti -s com.microsoft.VSCode .nanorc all
duti -s com.microsoft.VSCode .nc all
duti -s com.microsoft.VSCode .ooc all
duti -s com.microsoft.VSCode .q all
duti -s com.microsoft.VSCode .rst all
duti -s com.microsoft.VSCode .rest all
duti -s com.microsoft.VSCode .rest.txt all
duti -s com.microsoft.VSCode .rst.txt all
duti -s com.microsoft.VSCode .sed all
duti -s com.microsoft.VSCode .wisp all
duti -s com.microsoft.VSCode .prg all
duti -s com.microsoft.VSCode .ch all
duti -s com.microsoft.VSCode .prw all
duti -s com.microsoft.VSCode .css all
duti -s com.microsoft.VSCode .go all
duti -s com.microsoft.VSCode .java all
duti -s com.microsoft.VSCode .js all
duti -s com.microsoft.VSCode .cfg all
duti -s com.microsoft.VSCode .json all
duti -s com.microsoft.VSCode .md all
duti -s com.microsoft.VSCode .py all
duti -s com.microsoft.VSCode .rb all
duti -s com.microsoft.VSCode .rs all
duti -s com.microsoft.VSCode .sh all
duti -s com.microsoft.VSCode .swift all
duti -s com.microsoft.VSCode .txt all
duti -s com.microsoft.VSCode .conf all
duti -s com.microsoft.VSCode .properties all
duti -s com.microsoft.VSCode .yaml all
duti -s com.microsoft.VSCode .yml all
duti -s com.microsoft.VSCode .xml all
duti -s com.microsoft.VSCode .nomad all
duti -s com.microsoft.VSCode .Jenkinsfile all
duti -s com.microsoft.VSCode Jenkinsfile all
echo 'duti associations done'
